import type { Metadata } from "next";
import { Epilogue } from "next/font/google";
import DefaultLayout from "@/components/layouts/DefaultLayout";
import "./styles/globals.css";
import MobileOnlyAlert from "@/components/custom-ui/MobileOnlyAlert";

const epilogue = Epilogue({
  variable: "--font-epilogue",
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body className={`${epilogue.className} antialiased`}>
        <DefaultLayout className="hidden xl:block">{children}</DefaultLayout>

        <MobileOnlyAlert className="block xl:hidden" />
      </body>
    </html>
  );
}
